#!/usr/bin/env uvrun
# /// script
# requires-python = ">=3.8"
# dependencies = []
# ///

"""
Nuke script: Reduces project to minimum files needed for complete regeneration.

Keeps:
  - README.md
  - ./readme/ (use-case documentation)
  - ./the-system/ (scripts and prompts)
  - .git/ and .gitignore (version control)

Deletes (all regeneratable):
  - ./reqs/ (generated by reqs-gen.py)
  - ./tests/ (generated by software-construction.py)
  - ./code/ (generated by software-construction.py)
  - ./release/ (generated by build.py)
  - ./tmp/ (temporary files)
  - ./report/ (generated reports)
  - Any other directories not in the keep list
"""

import sys
import os
import shutil
from pathlib import Path

# Fix Windows console encoding for Unicode characters
if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

# Directories to keep (relative to project root)
KEEP_DIRS = {
    'readme',
    'the-system',
    '.git',
}

# Files to keep in root
KEEP_ROOT_FILES = {
    'README.md',
    '.gitignore',
}

def get_project_root():
    """Get the project root directory (parent of the-system)."""
    script_path = Path(__file__).resolve()
    return script_path.parent.parent.parent

def nuke_project():
    """Remove all regeneratable files and directories."""
    project_root = get_project_root()

    print(f"🔥 Nuking project at: {project_root}")
    print()
    print("📌 Keeping:")
    print(f"   - README.md")
    for keep_dir in sorted(KEEP_DIRS):
        print(f"   - ./{keep_dir}/")
    print()

    # Find directories to delete
    dirs_to_delete = []
    for item in project_root.iterdir():
        if item.is_dir() and item.name not in KEEP_DIRS:
            dirs_to_delete.append(item)

    # Find root files to delete
    files_to_delete = []
    for item in project_root.iterdir():
        if item.is_file() and item.name not in KEEP_ROOT_FILES:
            files_to_delete.append(item)

    if not dirs_to_delete and not files_to_delete:
        print("✅ Project already clean -- nothing to delete")
        return

    print("🗑️  Deleting:")
    for dir_path in sorted(dirs_to_delete):
        print(f"   - ./{dir_path.name}/")
    for file_path in sorted(files_to_delete):
        print(f"   - {file_path.name}")
    print()

    # Confirm deletion
    response = input("⚠️  Proceed with deletion? [y/N]: ")
    if response.lower() != 'y':
        print("❌ Aborted")
        return

    # Delete directories
    for dir_path in dirs_to_delete:
        try:
            shutil.rmtree(dir_path)
            print(f"✓ Deleted ./{dir_path.name}/")
        except Exception as e:
            print(f"✗ Failed to delete ./{dir_path.name}/: {e}")

    # Delete files
    for file_path in files_to_delete:
        try:
            file_path.unlink()
            print(f"✓ Deleted {file_path.name}")
        except Exception as e:
            print(f"✗ Failed to delete {file_path.name}: {e}")

    print()
    print("✅ Project nuked successfully")
    print()
    print("To regenerate:")
    print("  1. uv run --script ./the-system/scripts/reqs-gen.py")
    print("  2. Review flows in ./reqs/")
    print("  3. uv run --script ./the-system/scripts/software-construction.py")

if __name__ == '__main__':
    try:
        nuke_project()
    except KeyboardInterrupt:
        print()
        print("❌ Aborted by user")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        sys.exit(1)
